import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import MediumLogoText from '../public/medium-logo-text.png'

const Home: NextPage = () => {
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Medium Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="flex justify-between items-center bg-yellow-400 border-y-black py-10 lg:py-0">
        <div className="px-10 space-y-5">
          <h1 className="text-6xl max-w-xl font-serif">
            <span className="underline decoration-black decoration-4">
              Medium
            </span>{' '}
            is the place to write, read and connect
          </h1>
          <h2>
            It&apos;s easy and free to post your thinking on any topic and
            connect with millions of readers
          </h2>
        </div>
        <img
          className="hidden lg:inline-flex h-32 "
          src={MediumLogoText.src}
          alt=""
        />
      </div>
    </div>
  )
}

export default Home
